# Connexion a la base de données
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/notes_frais_db
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# Désactiver les erreurs cors lors de l'envoi des données depuis le front
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://127.0.0.1:5500
quarkus.http.cors.methods=GET,POST
# Envoi des mails
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${MAILER_EMAIL}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${MAILER_EMAIL}
quarkus.mailer.password=${MAILER_PASSWORD}
quarkus.mailer.mock=false